// Build 3 through the real page: keys, notices and the heads-up display.
const { chromium } = require('./_playwright');
const URL = process.env.DTV_URL || 'http://127.0.0.1:8765/defend-the-village.html';
const sleep = ms => new Promise(r => setTimeout(r, ms));
(async () => {
  const browser = await chromium.launch({ args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
  const page = await (await browser.newContext({ viewport: { width: 1100, height: 700 } })).newPage(); const errs = [], log = [];
  const ok = (n, c, x) => { log.push((c ? 'PASS ' : 'FAIL ') + n + (x !== undefined ? '  [' + x + ']' : '')); console.log(log[log.length - 1]); };
  page.on('pageerror', e => errs.push('PAGEERROR: ' + e.message + '\n' + (e.stack || '').split('\n').slice(0, 6).join('\n')));
  page.on('console', m => { if (m.type() === 'error' && !/ERR_TUNNEL|Failed to load/.test(m.text())) errs.push(m.text()); });
  await page.goto(URL); await sleep(1500);
  ok('home change log is Build 3', /Build 3: the inn and the ruins/.test(await page.textContent('#home .side h2')));
  const fit = await page.evaluate(() => { const r = document.querySelector('#home .side').getBoundingClientRect(); return [Math.round(r.top), Math.round(r.bottom), innerHeight]; });
  ok('home notices fit the window', fit[0] >= 0 && fit[1] <= fit[2] + 8, fit.join('/'));
  await page.evaluate(() => localStorage.removeItem('dtv-save'));
  await page.fill('#name', 'Matt'); await page.click('#btnSolo'); await sleep(5000);
  const g = f => page.evaluate(f), press = async (k, ms) => { await page.keyboard.press(k); await sleep(ms || 1500); };
  await g(() => { document.getElementById('dawn').hidden = true; });
  ok('dawn notice told us where the stone is', /stone is east of the village/.test(await page.textContent('#dawnLines')));
  await g(() => { const m = window.__dtv.me(); m.inv = [6, 18]; });
  await press('KeyI', 3000); ok('I opens the pack', !(await page.isHidden('#panel')) && /Your pack/.test(await page.textContent('#panelTitle')), await page.textContent('#panelTitle'));
  await press('Digit1'); ok('1 takes the club in hand', await g(() => window.__dtv.me().wpn) === 6);
  await press('Digit1'); ok('then 1 puts the pot on', await g(() => window.__dtv.me().head) === 18, await g(() => window.__dtv.me().inv.join()));
  await g(() => { window.__dtv.me().abCd = 0; }); await sleep(4000); ok('the heads-up display names the gear and the trick', /club, cooking pot/.test(await page.textContent('#hudGear')) && /Wallop: ready/.test(await page.textContent('#hudAb')), await page.textContent('#hudGear') + ' | ' + await page.textContent('#hudAb'));
  await press('KeyI', 3500); ok('I closes it again', await page.isHidden('#panel'));
  await g(() => { const d = window.__dtv, m = d.me(); m.x = 40; m.z = 0; m.r = 0; const u = d.sim.spawnUndead(0, 40, 1.5); u.state = 'walk'; u.t = 0; u.cd = 99; });
  await press('ShiftLeft', 1500); const a1 = await g(() => { const d = window.__dtv; return { cd: d.me().abCd, stun: d.S.undead[0] ? d.S.undead[0].stun : -1 }; });
  ok('Shift wallops the shambler (stunned, or flattened outright) and the trick is on its wait', a1.cd > 0 && (a1.stun > 0 || a1.stun === -1), JSON.stringify(a1));
  ok('the display counts the wait down', /Wallop in \d+s/.test(await page.textContent('#hudAb')), await page.textContent('#hudAb'));
  await g(() => { const d = window.__dtv; d.S.undead.length = 0; d.me().abCd = 0; const u = d.sim.spawnUndead(0, 40, 1.5); u.state = 'walk'; u.t = 0; u.cd = 99; });
  await page.mouse.click(600, 420, { button: 'right' }); await sleep(1500);
  ok('right-click does the same', await g(() => window.__dtv.me().abCd) > 0);
  await g(() => { window.__dtv.S.undead.length = 0; });
  await press('KeyG'); ok('G with nothing to use says so', /Nothing to use/.test(await page.textContent('#bannerTitle')));
  await press('KeyQ'); ok('Q without the book says what it needs', /No orders yet/.test(await page.textContent('#bannerTitle')));
  await g(() => { const d = window.__dtv, m = d.me(); m.books[6] = 3; }); await press('KeyQ'); ok('Q with the book: hold here', await g(() => window.__dtv.me().ord) === 1 && /Hold here/.test(await page.textContent('#bannerTitle')));
  await press('KeyT'); ok('T without a posse says so', /No posse/.test(await page.textContent('#bannerTitle')));
  await g(() => { const d = window.__dtv, m = d.me(); m.x = 12.9; m.z = 11.4; });
  await page.keyboard.down('KeyE'); await sleep(1800); await page.keyboard.up('KeyE'); await sleep(800);
  ok('E opens the storehouse', /storehouse/i.test(await page.textContent('#panelTitle')), await page.textContent('#panelTitle'));
  await press('Digit9'); ok('9 turns to the arms rack', /arms rack/i.test(await page.textContent('#panelTitle')), await page.textContent('#panelTitle'));
  await press('Digit1'); ok('1 puts the club on the rack', await g(() => window.__dtv.S.items.join()) === '6' && await g(() => window.__dtv.me().wpn) === 0, await g(() => window.__dtv.S.items.join()));
  await g(() => { const d = window.__dtv, m = d.me(); m.x = 13.4; m.z = 20.4; }); await page.keyboard.down('KeyE'); await sleep(1800); await page.keyboard.up('KeyE'); await sleep(800);
  ok('the library notice shows', /library/i.test(await page.textContent('#panelTitle'))); await g(() => { window.__dtv.me().books = new Array(10).fill(0); });
  await press('Digit0'); ok('0 takes the tenth book', await g(() => window.__dtv.me().books[9]) === 1, await g(() => window.__dtv.me().books.join('')));
  await g(() => { const d = window.__dtv, m = d.me(); m.x = 91.6; m.z = 10; }); await press('Escape', 300);
  await page.keyboard.down('KeyD'); await sleep(2500); const edge = await page.textContent('#promptText'); await page.keyboard.up('KeyD');
  ok('walking into the hedge explains itself', /thorn hedge/.test(edge) && await g(() => window.__dtv.me().x) <= 92, edge);
  // the handbook, the controls and the keep
  await press('Escape', 2500); ok('Esc with nothing open brings up the handbook', !(await page.isHidden('#menu')) && /paused/.test(await page.textContent('#menuNote')), await page.textContent('#menuNote'));
  ok('the guide is there, with the keys named', /The short version/.test(await page.textContent('#menuBody')) && (await page.locator('#menuBody kbd').count()) > 8);
  const t0 = await g(() => window.__dtv.S.timeLeft); await sleep(3000); ok('alone, the day stands still while it is open', Math.abs(await g(() => window.__dtv.S.timeLeft) - t0) < 0.01);
  await page.click('#menuTabs [data-tab=keys]'); await sleep(1200); ok('the controls list every action', (await page.locator('#menuBody [data-bind]').count()) >= 16);
  await page.click('#menuBody [data-bind=interact]'); await sleep(900); await page.keyboard.press('KeyC'); await sleep(1500);
  ok('E can be changed to C', await g(() => window.__dtv.BIND.interact.join()) === 'KeyC', await page.textContent('#menuBody .bind'));
  await page.click('#menuBody [data-bind=eat]'); await sleep(900); await page.keyboard.press('KeyC'); await sleep(1500);
  ok('giving C to something else takes it from the first', await g(() => window.__dtv.BIND.eat.join()) === 'KeyC' && await g(() => window.__dtv.BIND.interact.length) === 0 && /no key set/.test(await page.textContent('#menuBody .bind')));
  await page.click('#menuBody [data-bind=interact]'); await sleep(900); await page.keyboard.press('KeyV'); await sleep(1200);
  await page.click('#menuTabs [data-tab=opt]'); await sleep(900); await page.uncheck('#optTags'); ok('options are kept', await g(() => JSON.parse(localStorage.getItem('dtv-opt')).tags) === false); await page.check('#optTags');
  await page.click('#btnMenuClose'); await sleep(1500); ok('closing it carries on', await page.isHidden('#menu'));
  await g(() => { const d = window.__dtv, m = d.me(); const t = d.trees.filter(t => t.alive && t.x < -34)[0]; m.x = t.x + 1.5; m.z = t.z; m.wood = 0; }); await sleep(1500);
  ok('the prompt names the new key', /Hold V to chop/.test(await page.textContent('#promptText')), await page.textContent('#promptText'));
  await page.keyboard.down('KeyV'); await sleep(6000); await page.keyboard.up('KeyV'); ok('and the new key works', await g(() => window.__dtv.me().wood) > 0, await g(() => window.__dtv.me().wood));
  await press('Escape', 1500); await page.click('#menuTabs [data-tab=keys]'); await sleep(600); await page.click('#menuBody [data-bind="!reset"]'); await sleep(900); ok('the usual keys come back', await g(() => window.__dtv.BIND.interact.join()) === 'KeyE'); await page.click('#btnMenuClose'); await sleep(800);
  await g(() => { const d = window.__dtv, m = d.me(); m.x = 0; m.z = 8; d.S.undead.length = 0; }); await sleep(3000);
  const k0 = await g(() => window.__dtv.GFX.keep.alpha);
  await g(() => { const d = window.__dtv; const u = d.sim.spawnUndead(0, 0.5, -4.4); u.state = 'walk'; u.t = 0; u.cd = 99; }); await sleep(4000);
  const k1 = await g(() => window.__dtv.GFX.keep.alpha); await page.screenshot({ path: 'test/shots/b3-keepfade.png' });
  ok('the keep is solid until something is behind it, then see-through', k0 > 0.98 && k1 < 0.5, k0.toFixed(2) + ' -> ' + k1.toFixed(2));
  await g(() => { const d = window.__dtv, m = d.me(); d.S.undead.length = 0; m.inv = [7, 13, 24]; m.wpn = 6; }); await press('KeyX', 2000); ok('X swaps to the next weapon in the pack', await g(() => window.__dtv.me().wpn) === 7 && await g(() => window.__dtv.me().inv.includes(6)), await g(() => window.__dtv.me().inv.join()));
  await press('KeyI', 2500); ok('the pack shows slots', (await page.locator('#panelOpts .slot').count()) === 11 && (await page.locator('#panelOpts button.slot.locked').count()) === 1, await page.locator('#panelOpts .slot').count());
  await page.click('#panelOpts button.slot.locked'); await sleep(1200); ok('a bow without the book says what it needs', /needs rank 1 of Slings/.test(await page.textContent('#bannerSub')), await page.textContent('#bannerSub'));
  await page.screenshot({ path: 'test/shots/b3-pack.png' });
  await page.click('#panelOpts .drop >> nth=0'); await sleep(1500); ok('the cross drops a thing on the ground', await g(() => window.__dtv.S.drops.length) === 1 && await g(() => window.__dtv.me().inv.length) === 2);
  await press('Escape', 800);
  const tags = await g(() => document.querySelectorAll('#labels .nm').length); ok('no name tag over your own head', tags === 0, tags);
  await page.screenshot({ path: 'test/shots/b3-ui3.png' });
  console.log(log.filter(l => l.startsWith('FAIL')).length + ' failed'); console.log(errs.length ? errs.join('\n') : 'no errors');
  await browser.close();
})();
